name: Bug Report
description: Report issues and bugs encountered while using Slimefun 4
labels:
  - "🐞 Bug"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for using the Slimefun issue tracking system!

        Before reporting, please confirm:
        - You have checked if the [Latest Version](https://github.com/SaanPrasanna/Slimefun4/releases) has already fixed the issue you're encountering.
        - You have searched [Existing Issues](https://github.com/SaanPrasanna/Slimefun4/issues) to see if a similar problem has already been reported.
        
        If your feedback is vague or does not follow the template, it may be closed without notice.

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Provide a detailed description of the issue you encountered.
    validations:
      required: true

  - type: dropdown
    id: reproducibility
    attributes:
       label: Reproducibility
       description: Select how often this issue occurs.
       options:
         - Unable to reproduce
         - Rarely
         - Occasionally
         - Always
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Briefly explain how we can reproduce this issue.
      placeholder: |
        Briefly explain how we can reproduce this issue.
        You can use a 1. 2. 3. list format or any other appropriate style.
        If the issue is hard to reproduce, please describe the context when it occurred.
    validations:
      required: true

  - type: dropdown
    id: server-platform-type
    attributes:
      label: Server Platform Type
      description: |
        Select the server software you are using, e.g., `Paper`.
        Note: This fork does not support **hybrid servers** (such as Arclight, CatServer, etc., that allow both plugins and mods). Please resolve such issues yourself.
      options:
        - Paper
        - Leaves
        - Purpur
        - Airplane
        - Pufferfish
        - Leaf
        - Mirai
        - Other (Please specify in the "Issue Description")
    validations:
      required: true

  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      options:
        - 1.21.x
        - 1.20.x
        - 1.19.x
        - 1.18.x
        - 1.17.x
        - 1.16.x
        - Older (Please specify in the "Issue Description")
    validations:
      required: true

  - type: textarea
    id: slimefun-version
    validations:
      required: true
    attributes:
      label: Slimefun Version
      description: |
        **Do not write "latest version", otherwise your feedback will be closed immediately.**
        Please provide a screenshot or copy the output of the "/sf versions" command.
      placeholder: Slimefun (English Fork) 2025.1

  - type: textarea
    id: other-plugin
    attributes:
      label: Server Plugin List
      description: Provide your server's plugin list (can be obtained by running /plugins).
      placeholder: |
        Plugin: Version

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: You can add any other relevant information here.
