name: Translation Feedback
description: Report issues with English translations or missing text
labels:
- "📜 Translation"

body:
- type: markdown
  attributes:
    value: |
      Thank you for helping us improve our English translation!
      
      Before reporting, please confirm:
      - You have checked if the [Latest Version](https://github.com/SaanPrasanna/Slimefun4/releases) has already fixed the issue.
      - You have searched [Existing Issues](https://github.com/SaanPrasanna/Slimefun4/issues) to see if it was already reported.

- type: textarea
  id: issue-description
  attributes:
    label: Translation Issue Description
    description: Describe the translation error or missing text.
  validations:
    required: true

- type: textarea
  id: reproduce
  attributes:
    label: Location of Error/Missing Text
    description: Briefly explain where this error or missing text can be found in-game.
  validations:
    required: true

- type: textarea
  id: slimefun-version
  validations:
    required: true
  attributes:
    label: Slimefun Version
    description: |
      **Do not write "latest version", otherwise your feedback will be closed immediately.**
      Please provide a screenshot or copy the output of the "/sf versions" command.
    placeholder: Slimefun (English Fork) 2025.1

- type: textarea
  id: additional
  attributes:
    label: Additional Information
    description: You can add any other relevant information here.
